from app.config.database import db
from datetime import datetime

class Schedule(db.Model):
    """
    Schedule Model - Normalized to 3NF
    
    Represents time blocks in user's calendar including:
    - Class sessions (from courses)
    - Study sessions (AI-generated or manual)
    - Break periods
    
    3NF Compliance:
    - 1NF: All attributes are atomic
    - 2NF: No partial dependencies (all attributes depend on schedule_id)
    - 3NF: No transitive dependencies
    """
    __tablename__ = 'schedules'
    
    # Primary Key
    schedule_id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    
    # Foreign Keys
    user_id = db.Column(db.Integer, db.ForeignKey('users.user_id', ondelete='CASCADE'), nullable=False, index=True)
    task_id = db.Column(db.Integer, db.ForeignKey('tasks.task_id', ondelete='SET NULL'), nullable=True, index=True)
    
    # Schedule Information
    date = db.Column(db.Date, nullable=False, index=True)
    start_time = db.Column(db.Time, nullable=False)
    end_time = db.Column(db.Time, nullable=False)
    
    # Block type: class, study, break
    block_type = db.Column(db.Enum('class', 'study', 'break', name='block_type_enum'), nullable=False, default='study')
    
    # Title/description of the block
    title = db.Column(db.String(255), nullable=True)
    
    # Color for the schedule block (hex color code)
    color = db.Column(db.String(7), nullable=True, default='#667eea')
    
    # Whether this was auto-generated by AI or manually created
    is_auto_generated = db.Column(db.Boolean, default=False, nullable=False)
    
    # Timestamp
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    
    def __repr__(self):
        return f'<Schedule {self.title} on {self.date}>'
    
    def to_dict(self, include_task=False):
        """Convert schedule object to dictionary"""
        schedule_dict = {
            'schedule_id': self.schedule_id,
            'user_id': self.user_id,
            'task_id': self.task_id,
            'date': self.date.isoformat() if self.date else None,
            'start_time': self.start_time.isoformat() if self.start_time else None,
            'end_time': self.end_time.isoformat() if self.end_time else None,
            'block_type': self.block_type,
            'title': self.title,
            'color': self.color,
            'is_auto_generated': self.is_auto_generated,
            'created_at': self.created_at.isoformat() if self.created_at else None
        }
        
        # Optionally include task information
        if include_task and self.task_id:
            from app.models.task import Task
            task = Task.query.get(self.task_id)
            if task:
                schedule_dict['task'] = {
                    'task_id': task.task_id,
                    'title': task.title,
                    'priority': task.priority,
                    'deadline': task.deadline.isoformat() if task.deadline else None
                }
        
        return schedule_dict
